package com.example.apnivehicle.repository

import com.example.apnivehicle.models.Vehicle

/**
 * Temporary seed data — 125 vehicles for the Pakistani market.
 * Used for development, testing, and prediction model training.
 */
object SampleVehicleData {

    private val sampleImages = listOf(
        "https://images.unsplash.com/photo-1623859627248-cb5f1d391f4d?q=80&w=1000",
        "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?q=80&w=1000",
        "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1000",
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1000",
        "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1000",
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1000",
        "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1000",
        "https://images.unsplash.com/photo-1502877338535-766e1452684a?q=80&w=1000",
        "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?q=80&w=1000",
        "https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=1000"
    )

    fun getAll(): List<Vehicle> = listOf(
        // ════════════════════════════════════════════════════════════════════════
        //  TOYOTA (25 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Toyota Corolla XLi 2019", price = 3200000, city = "Lahore", year = 2019,
            imageUri = sampleImages[0], brand = "Toyota", model = "Corolla XLi", mileage = 45000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-001", sellerPhone = "0300-1234567",
            sellerRating = 4.8f, sellerReviewCount = 12),
        Vehicle(title = "Toyota Corolla GLi 2020", price = 3800000, city = "Karachi", year = 2020,
            imageUri = sampleImages[1], brand = "Toyota", model = "Corolla GLi", mileage = 32000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-002", sellerPhone = "0321-9876543",
            sellerRating = 4.5f, sellerReviewCount = 8),
        Vehicle(title = "Toyota Corolla Altis 2021", price = 4500000, city = "Islamabad", year = 2021,
            imageUri = sampleImages[2], brand = "Toyota", model = "Corolla Altis", mileage = 22000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Pearl White", numberOfOwners = 1, sellerId = "seller-003", sellerPhone = "0333-5555666",
            sellerRating = 4.9f, sellerReviewCount = 20),
        Vehicle(title = "Toyota Corolla Grande 2022", price = 5200000, city = "Lahore", year = 2022,
            imageUri = sampleImages[3], brand = "Toyota", model = "Corolla Grande", mileage = 15000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-004", sellerPhone = "0345-7778899",
            sellerRating = 5f, sellerReviewCount = 35),
        Vehicle(title = "Toyota Yaris GLi 2021", price = 3100000, city = "Faisalabad", year = 2021,
            imageUri = sampleImages[4], brand = "Toyota", model = "Yaris", mileage = 28000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Red", numberOfOwners = 1, sellerId = "seller-005", sellerPhone = "0301-2223344",
            sellerRating = 4.3f, sellerReviewCount = 5),
        Vehicle(title = "Toyota Vitz 2020", price = 2200000, city = "Karachi", year = 2020,
            imageUri = sampleImages[5], brand = "Toyota", model = "Vitz", mileage = 40000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Silver", numberOfOwners = 2, sellerId = "seller-006", sellerPhone = "0311-4445566",
            sellerRating = 4.0f, sellerReviewCount = 3),
        Vehicle(title = "Toyota Aqua 2019", price = 2400000, city = "Lahore", year = 2019,
            imageUri = sampleImages[6], brand = "Toyota", model = "Aqua", mileage = 55000,
            transmission = "CVT (Auto)", fuelType = "Hybrid (Petrol+Electric)", condition = "Used — Good",
            color = "Blue", numberOfOwners = 1, sellerId = "seller-007", sellerPhone = "0322-8889900",
            sellerRating = 4.6f, sellerReviewCount = 15),
        Vehicle(title = "Toyota Prius 2020", price = 3500000, city = "Islamabad", year = 2020,
            imageUri = sampleImages[7], brand = "Toyota", model = "Prius", mileage = 38000,
            transmission = "CVT (Auto)", fuelType = "Hybrid (Petrol+Electric)", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-008", sellerPhone = "0334-1112233",
            sellerRating = 4.7f, sellerReviewCount = 18),
        Vehicle(title = "Toyota Fortuner 2.8 2021", price = 8500000, city = "Karachi", year = 2021,
            imageUri = sampleImages[8], brand = "Toyota", model = "Fortuner", mileage = 30000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-009", sellerPhone = "0346-3334455",
            sellerRating = 4.9f, sellerReviewCount = 25),
        Vehicle(title = "Toyota Fortuner Legender 2023", price = 12500000, city = "Lahore", year = 2023,
            imageUri = sampleImages[9], brand = "Toyota", model = "Fortuner Legender", mileage = 8000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-010", sellerPhone = "0300-6667788",
            sellerRating = 5f, sellerReviewCount = 40),
        Vehicle(title = "Toyota Hilux Revo 2022", price = 7800000, city = "Rawalpindi", year = 2022,
            imageUri = sampleImages[0], brand = "Toyota", model = "Hilux Revo", mileage = 25000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-011", sellerPhone = "0312-5556677",
            sellerRating = 4.8f, sellerReviewCount = 22),
        Vehicle(title = "Toyota Hilux Single Cab 2020", price = 4200000, city = "Multan", year = 2020,
            imageUri = sampleImages[1], brand = "Toyota", model = "Hilux Single Cab", mileage = 60000,
            transmission = "Manual", fuelType = "Diesel", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-012", sellerPhone = "0323-9990011",
            sellerRating = 4.2f, sellerReviewCount = 6),
        Vehicle(title = "Toyota Land Cruiser V8 2019", price = 22000000, city = "Karachi", year = 2019,
            imageUri = sampleImages[2], brand = "Toyota", model = "Land Cruiser V8", mileage = 48000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Good",
            color = "Black", numberOfOwners = 2, sellerId = "seller-013", sellerPhone = "0335-2223344",
            sellerRating = 4.5f, sellerReviewCount = 10),
        Vehicle(title = "Toyota Prado TX 2021", price = 14500000, city = "Lahore", year = 2021,
            imageUri = sampleImages[3], brand = "Toyota", model = "Prado TX", mileage = 20000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "Pearl White", numberOfOwners = 1, sellerId = "seller-014", sellerPhone = "0341-7778899",
            sellerRating = 5f, sellerReviewCount = 30),
        Vehicle(title = "Toyota Camry 2020", price = 6500000, city = "Islamabad", year = 2020,
            imageUri = sampleImages[4], brand = "Toyota", model = "Camry", mileage = 35000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-015", sellerPhone = "0313-4445566",
            sellerRating = 4.7f, sellerReviewCount = 16),
        Vehicle(title = "Toyota Hiace 2021", price = 5800000, city = "Peshawar", year = 2021,
            imageUri = sampleImages[5], brand = "Toyota", model = "Hiace", mileage = 42000,
            transmission = "Manual", fuelType = "Diesel", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-016", sellerPhone = "0342-8889900",
            sellerRating = 4.3f, sellerReviewCount = 7),
        Vehicle(title = "Toyota Rush 2022", price = 5200000, city = "Karachi", year = 2022,
            imageUri = sampleImages[6], brand = "Toyota", model = "Rush", mileage = 18000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-017", sellerPhone = "0324-1112233",
            sellerRating = 4.6f, sellerReviewCount = 14),
        Vehicle(title = "Toyota C-HR 2021", price = 5800000, city = "Lahore", year = 2021,
            imageUri = sampleImages[7], brand = "Toyota", model = "C-HR", mileage = 22000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Orange", numberOfOwners = 1, sellerId = "seller-018", sellerPhone = "0300-3334455",
            sellerRating = 4.8f, sellerReviewCount = 19),
        Vehicle(title = "Toyota RAV4 2022", price = 7200000, city = "Islamabad", year = 2022,
            imageUri = sampleImages[8], brand = "Toyota", model = "RAV4", mileage = 16000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Blue", numberOfOwners = 1, sellerId = "seller-019", sellerPhone = "0311-6667788",
            sellerRating = 4.9f, sellerReviewCount = 27),
        Vehicle(title = "Toyota Corolla XLi 2018", price = 2600000, city = "Faisalabad", year = 2018,
            imageUri = sampleImages[9], brand = "Toyota", model = "Corolla XLi", mileage = 72000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Fair",
            color = "Grey", numberOfOwners = 2, sellerId = "seller-020", sellerPhone = "0321-5556677",
            sellerRating = 4.0f, sellerReviewCount = 4),
        Vehicle(title = "Toyota Corolla Altis 2017", price = 2300000, city = "Sialkot", year = 2017,
            imageUri = sampleImages[0], brand = "Toyota", model = "Corolla Altis", mileage = 85000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Fair",
            color = "White", numberOfOwners = 3, sellerId = "seller-021", sellerPhone = "0343-9990011",
            sellerRating = 3.8f, sellerReviewCount = 2),
        Vehicle(title = "Toyota Fortuner 2.8 2020", price = 7500000, city = "Quetta", year = 2020,
            imageUri = sampleImages[1], brand = "Toyota", model = "Fortuner", mileage = 45000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Good",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-022", sellerPhone = "0312-2223344",
            sellerRating = 4.4f, sellerReviewCount = 9),
        Vehicle(title = "Toyota Yaris Ativ 2022", price = 3400000, city = "Hyderabad", year = 2022,
            imageUri = sampleImages[2], brand = "Toyota", model = "Yaris", mileage = 12000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Champagne", numberOfOwners = 1, sellerId = "seller-023", sellerPhone = "0333-3334455",
            sellerRating = 4.6f, sellerReviewCount = 11),
        Vehicle(title = "Toyota Hilux Double Cab 2023", price = 8200000, city = "Karachi", year = 2023,
            imageUri = sampleImages[3], brand = "Toyota", model = "Hilux Double Cab", mileage = 5000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Brand New",
            color = "White", numberOfOwners = 1, sellerId = "seller-024", sellerPhone = "0345-6667788",
            sellerRating = 5f, sellerReviewCount = 45),
        Vehicle(title = "Toyota Land Cruiser 200 2018", price = 18000000, city = "Lahore", year = 2018,
            imageUri = sampleImages[4], brand = "Toyota", model = "Land Cruiser 200", mileage = 65000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Good",
            color = "Black", numberOfOwners = 2, sellerId = "seller-025", sellerPhone = "0300-8889900",
            sellerRating = 4.7f, sellerReviewCount = 13),

        // ════════════════════════════════════════════════════════════════════════
        //  HONDA (20 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Honda Civic Oriel 2021", price = 4200000, city = "Karachi", year = 2021,
            imageUri = sampleImages[5], brand = "Honda", model = "Civic Oriel", mileage = 25000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-026", sellerPhone = "0311-1112233",
            sellerRating = 5f, sellerReviewCount = 28),
        Vehicle(title = "Honda Civic VTi 2020", price = 3800000, city = "Lahore", year = 2020,
            imageUri = sampleImages[6], brand = "Honda", model = "Civic VTi", mileage = 35000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Good",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-027", sellerPhone = "0322-3334455",
            sellerRating = 4.5f, sellerReviewCount = 10),
        Vehicle(title = "Honda Civic RS 2023", price = 6500000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[7], brand = "Honda", model = "Civic RS", mileage = 5000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-028", sellerPhone = "0334-5556677",
            sellerRating = 4.9f, sellerReviewCount = 22),
        Vehicle(title = "Honda Civic 1.5 Turbo 2022", price = 5500000, city = "Karachi", year = 2022,
            imageUri = sampleImages[8], brand = "Honda", model = "Civic 1.5 Turbo", mileage = 18000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-029", sellerPhone = "0346-7778899",
            sellerRating = 4.8f, sellerReviewCount = 19),
        Vehicle(title = "Honda City Aspire 2021", price = 3200000, city = "Faisalabad", year = 2021,
            imageUri = sampleImages[9], brand = "Honda", model = "City Aspire", mileage = 30000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-030", sellerPhone = "0300-9990011",
            sellerRating = 4.3f, sellerReviewCount = 7),
        Vehicle(title = "Honda City 1.5 2020", price = 2800000, city = "Lahore", year = 2020,
            imageUri = sampleImages[0], brand = "Honda", model = "City 1.5", mileage = 42000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Blue", numberOfOwners = 2, sellerId = "seller-031", sellerPhone = "0312-2223344",
            sellerRating = 4.1f, sellerReviewCount = 5),
        Vehicle(title = "Honda City eHEV 2023", price = 4800000, city = "Karachi", year = 2023,
            imageUri = sampleImages[1], brand = "Honda", model = "City eHEV", mileage = 8000,
            transmission = "CVT (Auto)", fuelType = "Hybrid (Petrol+Electric)", condition = "Used — Excellent",
            color = "Pearl White", numberOfOwners = 1, sellerId = "seller-032", sellerPhone = "0323-4445566",
            sellerRating = 4.7f, sellerReviewCount = 15),
        Vehicle(title = "Honda Accord 2020", price = 6800000, city = "Islamabad", year = 2020,
            imageUri = sampleImages[2], brand = "Honda", model = "Accord", mileage = 32000,
            transmission = "CVT (Auto)", fuelType = "Hybrid (Petrol+Electric)", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-033", sellerPhone = "0335-6667788",
            sellerRating = 4.8f, sellerReviewCount = 21),
        Vehicle(title = "Honda BR-V 2022", price = 4200000, city = "Lahore", year = 2022,
            imageUri = sampleImages[3], brand = "Honda", model = "BR-V", mileage = 20000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-034", sellerPhone = "0341-8889900",
            sellerRating = 4.5f, sellerReviewCount = 12),
        Vehicle(title = "Honda HR-V 2023", price = 5200000, city = "Karachi", year = 2023,
            imageUri = sampleImages[4], brand = "Honda", model = "HR-V", mileage = 6000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-035", sellerPhone = "0301-1112233",
            sellerRating = 4.9f, sellerReviewCount = 26),
        Vehicle(title = "Honda Vezel 2021", price = 3600000, city = "Rawalpindi", year = 2021,
            imageUri = sampleImages[5], brand = "Honda", model = "Vezel", mileage = 28000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Green", numberOfOwners = 1, sellerId = "seller-036", sellerPhone = "0311-3334455",
            sellerRating = 4.4f, sellerReviewCount = 8),
        Vehicle(title = "Honda CR-V 2022", price = 7500000, city = "Lahore", year = 2022,
            imageUri = sampleImages[6], brand = "Honda", model = "CR-V", mileage = 15000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-037", sellerPhone = "0322-5556677",
            sellerRating = 4.8f, sellerReviewCount = 23),
        Vehicle(title = "Honda Fit 2020", price = 2100000, city = "Karachi", year = 2020,
            imageUri = sampleImages[7], brand = "Honda", model = "Fit", mileage = 38000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Yellow", numberOfOwners = 1, sellerId = "seller-038", sellerPhone = "0333-7778899",
            sellerRating = 4.2f, sellerReviewCount = 6),
        Vehicle(title = "Honda Jazz 2021", price = 2500000, city = "Islamabad", year = 2021,
            imageUri = sampleImages[8], brand = "Honda", model = "Jazz", mileage = 25000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Blue", numberOfOwners = 1, sellerId = "seller-039", sellerPhone = "0342-9990011",
            sellerRating = 4.5f, sellerReviewCount = 11),
        Vehicle(title = "Honda Civic Prosmatec 2019", price = 3200000, city = "Multan", year = 2019,
            imageUri = sampleImages[9], brand = "Honda", model = "Civic Prosmatec", mileage = 48000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Good",
            color = "Champagne", numberOfOwners = 2, sellerId = "seller-040", sellerPhone = "0300-2223344",
            sellerRating = 4.0f, sellerReviewCount = 3),
        Vehicle(title = "Honda City 1.3 2018", price = 1900000, city = "Sialkot", year = 2018,
            imageUri = sampleImages[0], brand = "Honda", model = "City 1.3", mileage = 68000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Fair",
            color = "Silver", numberOfOwners = 2, sellerId = "seller-041", sellerPhone = "0312-4445566",
            sellerRating = 3.9f, sellerReviewCount = 4),
        Vehicle(title = "Honda Civic 1.8 2017", price = 2400000, city = "Gujranwala", year = 2017,
            imageUri = sampleImages[1], brand = "Honda", model = "Civic 1.8", mileage = 78000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Fair",
            color = "White", numberOfOwners = 3, sellerId = "seller-042", sellerPhone = "0323-6667788",
            sellerRating = 3.7f, sellerReviewCount = 2),
        Vehicle(title = "Honda Accord 2019", price = 5200000, city = "Karachi", year = 2019,
            imageUri = sampleImages[2], brand = "Honda", model = "Accord", mileage = 42000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Good",
            color = "Black", numberOfOwners = 2, sellerId = "seller-043", sellerPhone = "0334-8889900",
            sellerRating = 4.3f, sellerReviewCount = 9),
        Vehicle(title = "Honda Stepwgn 2020", price = 3800000, city = "Lahore", year = 2020,
            imageUri = sampleImages[3], brand = "Honda", model = "Stepwgn", mileage = 35000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Brown", numberOfOwners = 1, sellerId = "seller-044", sellerPhone = "0345-1112233",
            sellerRating = 4.4f, sellerReviewCount = 7),
        Vehicle(title = "Honda Odyssey 2021", price = 5500000, city = "Islamabad", year = 2021,
            imageUri = sampleImages[4], brand = "Honda", model = "Odyssey", mileage = 22000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Dark Blue", numberOfOwners = 1, sellerId = "seller-045", sellerPhone = "0301-3334455",
            sellerRating = 4.7f, sellerReviewCount = 14),

        // ════════════════════════════════════════════════════════════════════════
        //  SUZUKI (18 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Suzuki Alto VXR 2022", price = 1950000, city = "Islamabad", year = 2022,
            imageUri = sampleImages[5], brand = "Suzuki", model = "Alto VXR", mileage = 18000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-046", sellerPhone = "0311-5556677",
            sellerRating = 4.5f, sellerReviewCount = 8),
        Vehicle(title = "Suzuki Alto AGS 2023", price = 2200000, city = "Lahore", year = 2023,
            imageUri = sampleImages[6], brand = "Suzuki", model = "Alto AGS", mileage = 8000,
            transmission = "Semi-Automatic (AGS)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-047", sellerPhone = "0322-7778899",
            sellerRating = 4.6f, sellerReviewCount = 10),
        Vehicle(title = "Suzuki Cultus VXL 2021", price = 2100000, city = "Karachi", year = 2021,
            imageUri = sampleImages[7], brand = "Suzuki", model = "Cultus VXL", mileage = 30000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-048", sellerPhone = "0333-9990011",
            sellerRating = 4.3f, sellerReviewCount = 6),
        Vehicle(title = "Suzuki Cultus AGS 2022", price = 2400000, city = "Faisalabad", year = 2022,
            imageUri = sampleImages[8], brand = "Suzuki", model = "Cultus AGS", mileage = 20000,
            transmission = "Semi-Automatic (AGS)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Blue", numberOfOwners = 1, sellerId = "seller-049", sellerPhone = "0341-2223344",
            sellerRating = 4.5f, sellerReviewCount = 9),
        Vehicle(title = "Suzuki Swift GLX 2022", price = 2800000, city = "Lahore", year = 2022,
            imageUri = sampleImages[9], brand = "Suzuki", model = "Swift GLX", mileage = 15000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-050", sellerPhone = "0300-4445566",
            sellerRating = 4.7f, sellerReviewCount = 14),
        Vehicle(title = "Suzuki Swift Automatic 2023", price = 3200000, city = "Karachi", year = 2023,
            imageUri = sampleImages[0], brand = "Suzuki", model = "Swift Automatic", mileage = 5000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-051", sellerPhone = "0312-6667788",
            sellerRating = 4.8f, sellerReviewCount = 17),
        Vehicle(title = "Suzuki Wagon R VXL 2021", price = 1700000, city = "Rawalpindi", year = 2021,
            imageUri = sampleImages[1], brand = "Suzuki", model = "Wagon R VXL", mileage = 28000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-052", sellerPhone = "0323-8889900",
            sellerRating = 4.2f, sellerReviewCount = 5),
        Vehicle(title = "Suzuki Wagon R AGS 2022", price = 1950000, city = "Multan", year = 2022,
            imageUri = sampleImages[2], brand = "Suzuki", model = "Wagon R AGS", mileage = 18000,
            transmission = "Semi-Automatic (AGS)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-053", sellerPhone = "0334-1112233",
            sellerRating = 4.4f, sellerReviewCount = 7),
        Vehicle(title = "Suzuki Bolan VX 2020", price = 950000, city = "Peshawar", year = 2020,
            imageUri = sampleImages[3], brand = "Suzuki", model = "Bolan VX", mileage = 55000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Fair",
            color = "White", numberOfOwners = 2, sellerId = "seller-054", sellerPhone = "0342-3334455",
            sellerRating = 3.8f, sellerReviewCount = 3),
        Vehicle(title = "Suzuki Ravi 2021", price = 1050000, city = "Sialkot", year = 2021,
            imageUri = sampleImages[4], brand = "Suzuki", model = "Ravi", mileage = 42000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-055", sellerPhone = "0301-5556677",
            sellerRating = 4.0f, sellerReviewCount = 4),
        Vehicle(title = "Suzuki Jimny 2023", price = 5500000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[5], brand = "Suzuki", model = "Jimny", mileage = 3000,
            transmission = "Manual", fuelType = "Petrol", condition = "Brand New",
            color = "Green", numberOfOwners = 1, sellerId = "seller-056", sellerPhone = "0311-7778899",
            sellerRating = 5f, sellerReviewCount = 32),
        Vehicle(title = "Suzuki Vitara 2022", price = 4200000, city = "Lahore", year = 2022,
            imageUri = sampleImages[6], brand = "Suzuki", model = "Vitara", mileage = 15000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-057", sellerPhone = "0322-9990011",
            sellerRating = 4.6f, sellerReviewCount = 13),
        Vehicle(title = "Suzuki Ertiga 2023", price = 4500000, city = "Karachi", year = 2023,
            imageUri = sampleImages[7], brand = "Suzuki", model = "Ertiga", mileage = 6000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-058", sellerPhone = "0333-2223344",
            sellerRating = 4.7f, sellerReviewCount = 16),
        Vehicle(title = "Suzuki S-Presso 2022", price = 1400000, city = "Faisalabad", year = 2022,
            imageUri = sampleImages[8], brand = "Suzuki", model = "S-Presso", mileage = 22000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "Orange", numberOfOwners = 1, sellerId = "seller-059", sellerPhone = "0341-4445566",
            sellerRating = 4.1f, sellerReviewCount = 5),
        Vehicle(title = "Suzuki Mehran VX 2018", price = 700000, city = "Quetta", year = 2018,
            imageUri = sampleImages[9], brand = "Suzuki", model = "Mehran VX", mileage = 95000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Fair",
            color = "White", numberOfOwners = 3, sellerId = "seller-060", sellerPhone = "0312-6667788",
            sellerRating = 3.5f, sellerReviewCount = 1),
        Vehicle(title = "Suzuki Khyber 2017", price = 550000, city = "Gujranwala", year = 2017,
            imageUri = sampleImages[0], brand = "Suzuki", model = "Khyber", mileage = 110000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Fair",
            color = "Grey", numberOfOwners = 4, sellerId = "seller-061", sellerPhone = "0323-8889900",
            sellerRating = 3.3f, sellerReviewCount = 1),
        Vehicle(title = "Suzuki Alto 660cc 2021", price = 1600000, city = "Hyderabad", year = 2021,
            imageUri = sampleImages[1], brand = "Suzuki", model = "Alto 660cc", mileage = 32000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-062", sellerPhone = "0334-9990011",
            sellerRating = 4.2f, sellerReviewCount = 6),
        Vehicle(title = "Suzuki Every 2022", price = 2200000, city = "Lahore", year = 2022,
            imageUri = sampleImages[2], brand = "Suzuki", model = "Every", mileage = 20000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-063", sellerPhone = "0300-2223344",
            sellerRating = 4.3f, sellerReviewCount = 8),

        // ════════════════════════════════════════════════════════════════════════
        //  HYUNDAI (12 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Hyundai Elantra GLS 2022", price = 4800000, city = "Lahore", year = 2022,
            imageUri = sampleImages[3], brand = "Hyundai", model = "Elantra GLS", mileage = 18000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-064", sellerPhone = "0311-3334455",
            sellerRating = 4.7f, sellerReviewCount = 15),
        Vehicle(title = "Hyundai Elantra 2021", price = 4200000, city = "Karachi", year = 2021,
            imageUri = sampleImages[4], brand = "Hyundai", model = "Elantra", mileage = 28000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Blue", numberOfOwners = 1, sellerId = "seller-065", sellerPhone = "0322-5556677",
            sellerRating = 4.4f, sellerReviewCount = 9),
        Vehicle(title = "Hyundai Sonata 2022", price = 6200000, city = "Islamabad", year = 2022,
            imageUri = sampleImages[5], brand = "Hyundai", model = "Sonata", mileage = 15000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-066", sellerPhone = "0333-7778899",
            sellerRating = 4.8f, sellerReviewCount = 20),
        Vehicle(title = "Hyundai Tucson AWD 2023", price = 6800000, city = "Lahore", year = 2023,
            imageUri = sampleImages[6], brand = "Hyundai", model = "Tucson AWD", mileage = 8000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-067", sellerPhone = "0342-9990011",
            sellerRating = 4.9f, sellerReviewCount = 28),
        Vehicle(title = "Hyundai Tucson 2WD 2022", price = 5500000, city = "Karachi", year = 2022,
            imageUri = sampleImages[7], brand = "Hyundai", model = "Tucson 2WD", mileage = 20000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-068", sellerPhone = "0300-2223344",
            sellerRating = 4.6f, sellerReviewCount = 13),
        Vehicle(title = "Hyundai Tucson Ultimate 2023", price = 8200000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[8], brand = "Hyundai", model = "Tucson Ultimate", mileage = 5000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Brand New",
            color = "Dark Blue", numberOfOwners = 1, sellerId = "seller-069", sellerPhone = "0311-4445566",
            sellerRating = 5f, sellerReviewCount = 38),
        Vehicle(title = "Hyundai Santa Fe 2021", price = 7500000, city = "Lahore", year = 2021,
            imageUri = sampleImages[9], brand = "Hyundai", model = "Santa Fe", mileage = 25000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-070", sellerPhone = "0322-6667788",
            sellerRating = 4.7f, sellerReviewCount = 16),
        Vehicle(title = "Hyundai Staria 2023", price = 9500000, city = "Karachi", year = 2023,
            imageUri = sampleImages[0], brand = "Hyundai", model = "Staria", mileage = 6000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-071", sellerPhone = "0333-8889900",
            sellerRating = 4.8f, sellerReviewCount = 22),
        Vehicle(title = "Hyundai Ioniq 5 2023", price = 12000000, city = "Lahore", year = 2023,
            imageUri = sampleImages[1], brand = "Hyundai", model = "Ioniq 5", mileage = 3000,
            transmission = "Automatic", fuelType = "Electric", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-072", sellerPhone = "0345-1112233",
            sellerRating = 5f, sellerReviewCount = 42),
        Vehicle(title = "Hyundai Creta 2022", price = 4500000, city = "Faisalabad", year = 2022,
            imageUri = sampleImages[2], brand = "Hyundai", model = "Creta", mileage = 18000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-073", sellerPhone = "0301-3334455",
            sellerRating = 4.5f, sellerReviewCount = 11),
        Vehicle(title = "Hyundai i10 2021", price = 1800000, city = "Rawalpindi", year = 2021,
            imageUri = sampleImages[3], brand = "Hyundai", model = "i10", mileage = 30000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "Yellow", numberOfOwners = 1, sellerId = "seller-074", sellerPhone = "0312-5556677",
            sellerRating = 4.1f, sellerReviewCount = 5),
        Vehicle(title = "Hyundai Accent 2020", price = 1600000, city = "Multan", year = 2020,
            imageUri = sampleImages[4], brand = "Hyundai", model = "Accent", mileage = 45000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "Silver", numberOfOwners = 2, sellerId = "seller-075", sellerPhone = "0323-7778899",
            sellerRating = 4.0f, sellerReviewCount = 3),

        // ════════════════════════════════════════════════════════════════════════
        //  KIA (10 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Kia Sportage AWD 2022", price = 5500000, city = "Karachi", year = 2022,
            imageUri = sampleImages[5], brand = "KIA", model = "Sportage AWD", mileage = 18000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-076", sellerPhone = "0334-9990011",
            sellerRating = 4.8f, sellerReviewCount = 24),
        Vehicle(title = "Kia Sportage FWD 2023", price = 5800000, city = "Lahore", year = 2023,
            imageUri = sampleImages[6], brand = "KIA", model = "Sportage FWD", mileage = 8000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-077", sellerPhone = "0300-3334455",
            sellerRating = 4.7f, sellerReviewCount = 18),
        Vehicle(title = "Kia Sportage GT-Line 2023", price = 6800000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[7], brand = "KIA", model = "Sportage GT-Line", mileage = 5000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-078", sellerPhone = "0311-6667788",
            sellerRating = 5f, sellerReviewCount = 30),
        Vehicle(title = "Kia Picanto 2022", price = 1800000, city = "Faisalabad", year = 2022,
            imageUri = sampleImages[8], brand = "KIA", model = "Picanto", mileage = 22000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "Red", numberOfOwners = 1, sellerId = "seller-079", sellerPhone = "0322-8889900",
            sellerRating = 4.3f, sellerReviewCount = 7),
        Vehicle(title = "Kia Stonic 2023", price = 3200000, city = "Lahore", year = 2023,
            imageUri = sampleImages[9], brand = "KIA", model = "Stonic", mileage = 10000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Orange", numberOfOwners = 1, sellerId = "seller-080", sellerPhone = "0333-1112233",
            sellerRating = 4.6f, sellerReviewCount = 12),
        Vehicle(title = "Kia Sorento 2022", price = 7200000, city = "Karachi", year = 2022,
            imageUri = sampleImages[0], brand = "KIA", model = "Sorento", mileage = 20000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-081", sellerPhone = "0342-2223344",
            sellerRating = 4.7f, sellerReviewCount = 15),
        Vehicle(title = "Kia Carnival 2023", price = 9800000, city = "Lahore", year = 2023,
            imageUri = sampleImages[1], brand = "KIA", model = "Carnival", mileage = 8000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-082", sellerPhone = "0301-4445566",
            sellerRating = 4.9f, sellerReviewCount = 27),
        Vehicle(title = "Kia Seltos 2023", price = 4200000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[2], brand = "KIA", model = "Seltos", mileage = 12000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Blue", numberOfOwners = 1, sellerId = "seller-083", sellerPhone = "0312-5556677",
            sellerRating = 4.5f, sellerReviewCount = 10),
        Vehicle(title = "Kia Cerato 2022", price = 3500000, city = "Rawalpindi", year = 2022,
            imageUri = sampleImages[3], brand = "KIA", model = "Cerato", mileage = 18000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-084", sellerPhone = "0323-7778899",
            sellerRating = 4.4f, sellerReviewCount = 8),
        Vehicle(title = "Kia EV6 2023", price = 14500000, city = "Lahore", year = 2023,
            imageUri = sampleImages[4], brand = "KIA", model = "EV6", mileage = 2000,
            transmission = "Automatic", fuelType = "Electric", condition = "Brand New",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-085", sellerPhone = "0334-9990011",
            sellerRating = 5f, sellerReviewCount = 50),

        // ════════════════════════════════════════════════════════════════════════
        //  NISSAN (8 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Nissan Sunny 2021", price = 2200000, city = "Karachi", year = 2021,
            imageUri = sampleImages[5], brand = "Nissan", model = "Sunny", mileage = 32000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-086", sellerPhone = "0300-2223344",
            sellerRating = 4.2f, sellerReviewCount = 6),
        Vehicle(title = "Nissan X-Trail 2022", price = 5800000, city = "Lahore", year = 2022,
            imageUri = sampleImages[6], brand = "Nissan", model = "X-Trail", mileage = 20000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-087", sellerPhone = "0311-3334455",
            sellerRating = 4.6f, sellerReviewCount = 14),
        Vehicle(title = "Nissan Patrol 2021", price = 15000000, city = "Karachi", year = 2021,
            imageUri = sampleImages[7], brand = "Nissan", model = "Patrol", mileage = 35000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-088", sellerPhone = "0322-5556677",
            sellerRating = 4.8f, sellerReviewCount = 19),
        Vehicle(title = "Nissan Kicks 2023", price = 3800000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[8], brand = "Nissan", model = "Kicks", mileage = 8000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Orange", numberOfOwners = 1, sellerId = "seller-089", sellerPhone = "0333-7778899",
            sellerRating = 4.5f, sellerReviewCount = 11),
        Vehicle(title = "Nissan Juke 2020", price = 2800000, city = "Faisalabad", year = 2020,
            imageUri = sampleImages[9], brand = "Nissan", model = "Juke", mileage = 38000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Yellow", numberOfOwners = 2, sellerId = "seller-090", sellerPhone = "0341-9990011",
            sellerRating = 4.1f, sellerReviewCount = 5),
        Vehicle(title = "Nissan March 2021", price = 1500000, city = "Rawalpindi", year = 2021,
            imageUri = sampleImages[0], brand = "Nissan", model = "March", mileage = 28000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Purple", numberOfOwners = 1, sellerId = "seller-091", sellerPhone = "0312-2223344",
            sellerRating = 4.0f, sellerReviewCount = 4),
        Vehicle(title = "Nissan Navara 2022", price = 6500000, city = "Peshawar", year = 2022,
            imageUri = sampleImages[1], brand = "Nissan", model = "Navara", mileage = 22000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-092", sellerPhone = "0323-4445566",
            sellerRating = 4.6f, sellerReviewCount = 12),
        Vehicle(title = "Nissan Leaf 2022", price = 4500000, city = "Lahore", year = 2022,
            imageUri = sampleImages[2], brand = "Nissan", model = "Leaf", mileage = 15000,
            transmission = "Automatic", fuelType = "Electric", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-093", sellerPhone = "0334-6667788",
            sellerRating = 4.7f, sellerReviewCount = 16),

        // ════════════════════════════════════════════════════════════════════════
        //  DAIHATSU (6 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Daihatsu Mira 2021", price = 1400000, city = "Karachi", year = 2021,
            imageUri = sampleImages[3], brand = "Daihatsu", model = "Mira", mileage = 35000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-094", sellerPhone = "0301-8889900",
            sellerRating = 4.1f, sellerReviewCount = 5),
        Vehicle(title = "Daihatsu Mira ES 2022", price = 1700000, city = "Lahore", year = 2022,
            imageUri = sampleImages[4], brand = "Daihatsu", model = "Mira ES", mileage = 20000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Blue", numberOfOwners = 1, sellerId = "seller-095", sellerPhone = "0311-9990011",
            sellerRating = 4.2f, sellerReviewCount = 6),
        Vehicle(title = "Daihatsu Cuore 2020", price = 1100000, city = "Faisalabad", year = 2020,
            imageUri = sampleImages[5], brand = "Daihatsu", model = "Cuore", mileage = 48000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Fair",
            color = "Silver", numberOfOwners = 2, sellerId = "seller-096", sellerPhone = "0322-2223344",
            sellerRating = 3.8f, sellerReviewCount = 2),
        Vehicle(title = "Daihatsu Terios 2022", price = 3500000, city = "Islamabad", year = 2022,
            imageUri = sampleImages[6], brand = "Daihatsu", model = "Terios", mileage = 22000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-097", sellerPhone = "0333-3334455",
            sellerRating = 4.3f, sellerReviewCount = 7),
        Vehicle(title = "Daihatsu Move 2021", price = 1300000, city = "Rawalpindi", year = 2021,
            imageUri = sampleImages[7], brand = "Daihatsu", model = "Move", mileage = 30000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Green", numberOfOwners = 1, sellerId = "seller-098", sellerPhone = "0342-5556677",
            sellerRating = 4.0f, sellerReviewCount = 3),
        Vehicle(title = "Daihatsu Boon 2020", price = 1500000, city = "Multan", year = 2020,
            imageUri = sampleImages[8], brand = "Daihatsu", model = "Boon", mileage = 40000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Red", numberOfOwners = 2, sellerId = "seller-099", sellerPhone = "0300-4445566",
            sellerRating = 3.9f, sellerReviewCount = 3),

        // ════════════════════════════════════════════════════════════════════════
        //  CHANGAN (5 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Changan Alsvin Lumiere 2023", price = 3200000, city = "Lahore", year = 2023,
            imageUri = sampleImages[9], brand = "Changan", model = "Alsvin Lumiere", mileage = 8000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-100", sellerPhone = "0311-2223344",
            sellerRating = 4.5f, sellerReviewCount = 10),
        Vehicle(title = "Changan Alsvin Comfort 2022", price = 2600000, city = "Karachi", year = 2022,
            imageUri = sampleImages[0], brand = "Changan", model = "Alsvin Comfort", mileage = 18000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-101", sellerPhone = "0322-4445566",
            sellerRating = 4.3f, sellerReviewCount = 8),
        Vehicle(title = "Changan Oshan X7 2023", price = 5200000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[1], brand = "Changan", model = "Oshan X7", mileage = 6000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-102", sellerPhone = "0333-6667788",
            sellerRating = 4.6f, sellerReviewCount = 12),
        Vehicle(title = "Changan Karvaan 2022", price = 2200000, city = "Faisalabad", year = 2022,
            imageUri = sampleImages[2], brand = "Changan", model = "Karvaan", mileage = 25000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 1, sellerId = "seller-103", sellerPhone = "0341-7778899",
            sellerRating = 4.1f, sellerReviewCount = 5),
        Vehicle(title = "Changan CS75 Plus 2023", price = 5800000, city = "Lahore", year = 2023,
            imageUri = sampleImages[3], brand = "Changan", model = "CS75 Plus", mileage = 10000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-104", sellerPhone = "0300-8889900",
            sellerRating = 4.7f, sellerReviewCount = 15),

        // ════════════════════════════════════════════════════════════════════════
        //  MG (5 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "MG HS Trophy 2023", price = 5200000, city = "Karachi", year = 2023,
            imageUri = sampleImages[4], brand = "MG", model = "HS Trophy", mileage = 8000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-105", sellerPhone = "0312-9990011",
            sellerRating = 4.6f, sellerReviewCount = 13),
        Vehicle(title = "MG ZS EV 2023", price = 6800000, city = "Lahore", year = 2023,
            imageUri = sampleImages[5], brand = "MG", model = "ZS EV", mileage = 5000,
            transmission = "Automatic", fuelType = "Electric", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-106", sellerPhone = "0322-1112233",
            sellerRating = 4.8f, sellerReviewCount = 20),
        Vehicle(title = "MG HS Exclusive 2022", price = 4500000, city = "Islamabad", year = 2022,
            imageUri = sampleImages[6], brand = "MG", model = "HS Exclusive", mileage = 15000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-107", sellerPhone = "0333-2223344",
            sellerRating = 4.5f, sellerReviewCount = 10),
        Vehicle(title = "MG ZS 2022", price = 3500000, city = "Faisalabad", year = 2022,
            imageUri = sampleImages[7], brand = "MG", model = "ZS", mileage = 20000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Good",
            color = "Blue", numberOfOwners = 1, sellerId = "seller-108", sellerPhone = "0341-3334455",
            sellerRating = 4.2f, sellerReviewCount = 7),
        Vehicle(title = "MG Gloster 2023", price = 8500000, city = "Lahore", year = 2023,
            imageUri = sampleImages[8], brand = "MG", model = "Gloster", mileage = 5000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Brand New",
            color = "Black", numberOfOwners = 1, sellerId = "seller-109", sellerPhone = "0301-5556677",
            sellerRating = 4.7f, sellerReviewCount = 16),

        // ════════════════════════════════════════════════════════════════════════
        //  MITSUBISHI (5 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Mitsubishi Pajero 2020", price = 5500000, city = "Peshawar", year = 2020,
            imageUri = sampleImages[9], brand = "Mitsubishi", model = "Pajero", mileage = 55000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Good",
            color = "White", numberOfOwners = 2, sellerId = "seller-110", sellerPhone = "0312-7778899",
            sellerRating = 4.3f, sellerReviewCount = 8),
        Vehicle(title = "Mitsubishi Outlander 2022", price = 6200000, city = "Karachi", year = 2022,
            imageUri = sampleImages[0], brand = "Mitsubishi", model = "Outlander", mileage = 18000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-111", sellerPhone = "0322-8889900",
            sellerRating = 4.6f, sellerReviewCount = 14),
        Vehicle(title = "Mitsubishi Lancer GLX 2019", price = 1800000, city = "Lahore", year = 2019,
            imageUri = sampleImages[1], brand = "Mitsubishi", model = "Lancer GLX", mileage = 52000,
            transmission = "Manual", fuelType = "Petrol", condition = "Used — Good",
            color = "Grey", numberOfOwners = 2, sellerId = "seller-112", sellerPhone = "0333-1112233",
            sellerRating = 4.0f, sellerReviewCount = 4),
        Vehicle(title = "Mitsubishi Pajero Sport 2021", price = 7200000, city = "Islamabad", year = 2021,
            imageUri = sampleImages[2], brand = "Mitsubishi", model = "Pajero Sport", mileage = 30000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-113", sellerPhone = "0342-2223344",
            sellerRating = 4.7f, sellerReviewCount = 17),
        Vehicle(title = "Mitsubishi Eclipse Cross 2023", price = 6800000, city = "Lahore", year = 2023,
            imageUri = sampleImages[3], brand = "Mitsubishi", model = "Eclipse Cross", mileage = 8000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-114", sellerPhone = "0300-3334455",
            sellerRating = 4.8f, sellerReviewCount = 21),

        // ════════════════════════════════════════════════════════════════════════
        //  LUXURY / OTHER (19 vehicles)
        // ════════════════════════════════════════════════════════════════════════
        Vehicle(title = "Mercedes-Benz C300 2021", price = 9500000, city = "Lahore", year = 2021,
            imageUri = sampleImages[4], brand = "Mercedes-Benz", model = "C300", mileage = 25000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-115", sellerPhone = "0311-6667788",
            sellerRating = 4.9f, sellerReviewCount = 32),
        Vehicle(title = "Mercedes-Benz E300 2022", price = 14000000, city = "Karachi", year = 2022,
            imageUri = sampleImages[5], brand = "Mercedes-Benz", model = "E300", mileage = 15000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-116", sellerPhone = "0322-9990011",
            sellerRating = 5f, sellerReviewCount = 40),
        Vehicle(title = "Mercedes-Benz GLC 300 2023", price = 16000000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[6], brand = "Mercedes-Benz", model = "GLC 300", mileage = 5000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Brand New",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-117", sellerPhone = "0333-3334455",
            sellerRating = 5f, sellerReviewCount = 55),
        Vehicle(title = "BMW 520i 2022", price = 12000000, city = "Lahore", year = 2022,
            imageUri = sampleImages[7], brand = "BMW", model = "520i", mileage = 18000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-118", sellerPhone = "0345-5556677",
            sellerRating = 4.8f, sellerReviewCount = 25),
        Vehicle(title = "BMW X5 2021", price = 18000000, city = "Karachi", year = 2021,
            imageUri = sampleImages[8], brand = "BMW", model = "X5", mileage = 30000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Good",
            color = "White", numberOfOwners = 2, sellerId = "seller-119", sellerPhone = "0300-7778899",
            sellerRating = 4.5f, sellerReviewCount = 12),
        Vehicle(title = "Audi A4 2022", price = 8500000, city = "Lahore", year = 2022,
            imageUri = sampleImages[9], brand = "Audi", model = "A4", mileage = 20000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-120", sellerPhone = "0312-1112233",
            sellerRating = 4.7f, sellerReviewCount = 18),
        Vehicle(title = "Audi Q5 2023", price = 12500000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[0], brand = "Audi", model = "Q5", mileage = 8000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-121", sellerPhone = "0322-2223344",
            sellerRating = 4.9f, sellerReviewCount = 35),
        Vehicle(title = "Land Rover Range Rover 2022", price = 35000000, city = "Karachi", year = 2022,
            imageUri = sampleImages[1], brand = "Land Rover", model = "Range Rover", mileage = 15000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-122", sellerPhone = "0333-4445566",
            sellerRating = 5f, sellerReviewCount = 60),
        Vehicle(title = "Land Rover Defender 2023", price = 22000000, city = "Lahore", year = 2023,
            imageUri = sampleImages[2], brand = "Land Rover", model = "Defender", mileage = 6000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Brand New",
            color = "Green", numberOfOwners = 1, sellerId = "seller-123", sellerPhone = "0341-8889900",
            sellerRating = 5f, sellerReviewCount = 48),
        Vehicle(title = "Lexus RX 350 2022", price = 14000000, city = "Lahore", year = 2022,
            imageUri = sampleImages[3], brand = "Lexus", model = "RX 350", mileage = 18000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-124", sellerPhone = "0301-9990011",
            sellerRating = 4.8f, sellerReviewCount = 23),
        Vehicle(title = "Lexus LX 570 2021", price = 28000000, city = "Karachi", year = 2021,
            imageUri = sampleImages[4], brand = "Lexus", model = "LX 570", mileage = 25000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Black", numberOfOwners = 1, sellerId = "seller-125", sellerPhone = "0311-3334455",
            sellerRating = 5f, sellerReviewCount = 52),
        Vehicle(title = "Porsche Cayenne 2022", price = 25000000, city = "Lahore", year = 2022,
            imageUri = sampleImages[5], brand = "Porsche", model = "Cayenne", mileage = 12000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-126", sellerPhone = "0322-6667788",
            sellerRating = 4.9f, sellerReviewCount = 38),
        Vehicle(title = "Haval H6 2023", price = 5800000, city = "Lahore", year = 2023,
            imageUri = sampleImages[6], brand = "Haval", model = "H6", mileage = 8000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-127", sellerPhone = "0333-7778899",
            sellerRating = 4.6f, sellerReviewCount = 14),
        Vehicle(title = "Haval Jolion HEV 2023", price = 6200000, city = "Karachi", year = 2023,
            imageUri = sampleImages[7], brand = "Haval", model = "Jolion HEV", mileage = 5000,
            transmission = "Automatic", fuelType = "Hybrid (Petrol+Electric)", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-128", sellerPhone = "0342-9990011",
            sellerRating = 4.7f, sellerReviewCount = 18),
        Vehicle(title = "Proton X50 2023", price = 3800000, city = "Islamabad", year = 2023,
            imageUri = sampleImages[8], brand = "Proton", model = "X50", mileage = 10000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "Red", numberOfOwners = 1, sellerId = "seller-129", sellerPhone = "0300-1112233",
            sellerRating = 4.4f, sellerReviewCount = 9),
        Vehicle(title = "Ford Ranger 2022", price = 6500000, city = "Peshawar", year = 2022,
            imageUri = sampleImages[9], brand = "Ford", model = "Ranger", mileage = 25000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "Grey", numberOfOwners = 1, sellerId = "seller-130", sellerPhone = "0312-2223344",
            sellerRating = 4.5f, sellerReviewCount = 11),
        Vehicle(title = "Jeep Wrangler 2023", price = 12000000, city = "Lahore", year = 2023,
            imageUri = sampleImages[0], brand = "Jeep", model = "Wrangler", mileage = 5000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Brand New",
            color = "Green", numberOfOwners = 1, sellerId = "seller-131", sellerPhone = "0322-3334455",
            sellerRating = 4.8f, sellerReviewCount = 28),
        Vehicle(title = "BYD Atto 3 2023", price = 7500000, city = "Lahore", year = 2023,
            imageUri = sampleImages[1], brand = "BYD", model = "Atto 3", mileage = 3000,
            transmission = "Automatic", fuelType = "Electric", condition = "Brand New",
            color = "Blue", numberOfOwners = 1, sellerId = "seller-132", sellerPhone = "0333-5556677",
            sellerRating = 4.9f, sellerReviewCount = 42),
        Vehicle(title = "Geely Coolray 2023", price = 3500000, city = "Karachi", year = 2023,
            imageUri = sampleImages[2], brand = "Geely", model = "Coolray", mileage = 12000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-133", sellerPhone = "0345-7778899",
            sellerRating = 4.4f, sellerReviewCount = 8),
        Vehicle(title = "DFSK Glory 580 2022", price = 3800000, city = "Faisalabad", year = 2022,
            imageUri = sampleImages[3], brand = "DFSK", model = "Glory 580", mileage = 22000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Used — Good",
            color = "Silver", numberOfOwners = 1, sellerId = "seller-134", sellerPhone = "0300-3334455",
            sellerRating = 4.2f, sellerReviewCount = 6),
        Vehicle(title = "Isuzu D-Max 2022", price = 6200000, city = "Rawalpindi", year = 2022,
            imageUri = sampleImages[4], brand = "Isuzu", model = "D-Max", mileage = 20000,
            transmission = "Automatic", fuelType = "Diesel", condition = "Used — Excellent",
            color = "White", numberOfOwners = 1, sellerId = "seller-135", sellerPhone = "0311-4445566",
            sellerRating = 4.5f, sellerReviewCount = 10),
        Vehicle(title = "Suzuki Jimny 2024", price = 6200000, city = "Karachi", year = 2024,
            imageUri = sampleImages[5], brand = "Suzuki", model = "Jimny", mileage = 1000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Brand New",
            color = "Kinetic Yellow", numberOfOwners = 1, sellerId = "seller-136", sellerPhone = "0322-8889900",
            sellerRating = 5f, sellerReviewCount = 30),
        Vehicle(title = "Toyota Corolla Altis 2024", price = 5800000, city = "Lahore", year = 2024,
            imageUri = sampleImages[6], brand = "Toyota", model = "Corolla Altis", mileage = 2000,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Brand New",
            color = "Pearl White", numberOfOwners = 1, sellerId = "seller-137", sellerPhone = "0333-9990011",
            sellerRating = 5f, sellerReviewCount = 35),
        Vehicle(title = "Honda Civic RS 2024", price = 7800000, city = "Islamabad", year = 2024,
            imageUri = sampleImages[7], brand = "Honda", model = "Civic RS", mileage = 1500,
            transmission = "CVT (Auto)", fuelType = "Petrol", condition = "Brand New",
            color = "Rallye Red", numberOfOwners = 1, sellerId = "seller-138", sellerPhone = "0341-2223344",
            sellerRating = 5f, sellerReviewCount = 40),
        Vehicle(title = "Kia Sportage 2024", price = 6500000, city = "Karachi", year = 2024,
            imageUri = sampleImages[8], brand = "KIA", model = "Sportage 2023", mileage = 3000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Brand New",
            color = "Snow White Pearl", numberOfOwners = 1, sellerId = "seller-139", sellerPhone = "0300-5556677",
            sellerRating = 5f, sellerReviewCount = 38),
        Vehicle(title = "Hyundai Tucson 2024", price = 7200000, city = "Lahore", year = 2024,
            imageUri = sampleImages[9], brand = "Hyundai", model = "Tucson Ultimate", mileage = 2000,
            transmission = "Automatic", fuelType = "Petrol", condition = "Brand New",
            color = "Phantom Black", numberOfOwners = 1, sellerId = "seller-140", sellerPhone = "0312-7778899",
            sellerRating = 5f, sellerReviewCount = 45)
    )
}
